### ISSUE TITLE
Create a colours file

### ISSUE THREAD

**Issue by HaydenMCD** [HaydenMCD/jog-journal#27]
Create a file which stores all colours used in the app. All colours will be the same across all pages and easily changeable in the future.

**Comment by leggant** [comment]
I had a play with a solution. 

## Example `constants.css` file

```css
/* Base styles for the application, including colors and typography. */

:root {
  --primary: #4a90e2;
  --secondary: #50e3c2;
  --background: #222222;
  --text: #333333;
  --text-light: #ffffff;
  --border: #d1d1d1;
  --shadow: rgba(0, 0, 0, 0.1);
  --error: #e74c3c;
  --success: #2ecc71;
  --warning: #f39c12;
}
```

## Example `app.css` file

```css
@import './constants.css';

body {
  background-color: var(--background);
}

.wrapper {
  width: 100%;
  display: flex;
}
```
